name: docker build image

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-n-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build command
        run: |
          docker build -t my-csahrp-app .
          docker images
